# Generated by Django 5.0.6 on 2024-08-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
